watchlist:
  - code: "513120"
    name: "港股创新药ETF"
    market: "ETF"
  - code: "513350"
    name: "标普油气ETF富国"
    market: "ETF"
  - code: "600219"
    name: "南山铝业"
    market: "A"
  - code: "600965"
    name: "*ST福成"
    market: "A"
  - code: "601868"
    name: "中国能建"
    market: "A"
  - code: "002224"
    name: "三力士"
    market: "A"
  - code: "002594"
    name: "比亚迪"
    market: "A"
  - code: "002638"
    name: "勤上股份"
    market: "A"
  - code: "000338"
    name: "潍柴动力"
    market: "A"
  - code: "000880"
    name: "潍柴重机"
    market: "A"

